services:
  studio:
    env_file: .env
    build:
      context: .
      target: production
      args:
        VITE_BASE_SERVER_URL: ${VITE_BASE_SERVER_URL}
        VITE_CLOUDFLARE_TURNSTILE_ENABLED: ${VITE_CLOUDFLARE_TURNSTILE_ENABLED}
        VITE_CLOUDFLARE_TURNSTILE_SITE_KEY: ${VITE_CLOUDFLARE_TURNSTILE_SITE_KEY}
    ports:
      - 8080:8080
    networks:
      - squiglink

networks:
  squiglink:
    external: true
    name: squiglink
