services:
  studio:
    build: .
    ports:
      - 5173:5173
    volumes:
      - .:/studio
    networks:
      - squiglink
    environment:
      - VITE_BASE_API_URL=http://localhost:3000

networks:
  squiglink:
    external: true
    name: squiglink
