tasks:
  build:
    desc: Build the application.
    cmds:
      - docker compose run --rm studio pnpm vue-tsc --noEmit
      - docker compose run --rm studio pnpm vite build

  check:
    desc: Check everything.
    cmds:
      - task: check-formatting
      - task: check-linting
      - task: check-types
      - task: check-tests

  check-formatting:
    desc: Check formatting.
    cmds:
      - docker compose run --rm studio pnpm oxfmt --check {{.CLI_ARGS}}

  check-linting:
    desc: Check linting.
    cmds:
      - docker compose run --rm studio pnpm oxlint --deny-warnings {{.CLI_ARGS}}

  check-tests:
    desc: Check tests.
    cmds:
      - docker compose run --rm studio pnpm vitest run {{.CLI_ARGS}}

  check-types:
    desc: Check types.
    cmds:
      - docker compose run --rm studio pnpm vue-tsc --noEmit {{.CLI_ARGS}}

  fix-formatting:
    desc: Fix formatting.
    cmds:
      - docker compose run --rm studio pnpm oxfmt --write {{.CLI_ARGS}}

  install-dependencies:
    desc: Install dependencies.
    cmds:
      - docker compose run --rm studio pnpm install

  list:
    aliases:
      - default
    desc: List available tasks.
    cmds:
      - task --list

  start:
    desc: Start the application.
    cmds:
      - docker compose up

version: 3
