tasks:
  build:
    desc: Build the application.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun vue-tsc --noEmit
      - docker compose --file docker-compose.dev.yml run --rm studio bun vite build

  check:
    desc: Check everything.
    cmds:
      - task: check-formatting
      - task: check-linting
      - task: check-types
      - task: check-tests

  check-formatting:
    desc: Check formatting.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun oxfmt --check {{.CLI_ARGS}}

  check-linting:
    desc: Check linting.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun oxlint --deny-warnings {{.CLI_ARGS}}

  check-tests:
    desc: Check tests.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun test src/ {{.CLI_ARGS}}

  check-types:
    desc: Check types.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun vue-tsc --noEmit {{.CLI_ARGS}}

  fix-formatting:
    desc: Fix formatting.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun oxfmt --write {{.CLI_ARGS}}

  install-dependencies:
    desc: Install dependencies.
    cmds:
      - docker compose --file docker-compose.dev.yml run --rm studio bun install

  list:
    aliases:
      - default
    desc: List available tasks.
    cmds:
      - task --list

  start:
    desc: Start the application.
    cmds:
      - docker compose --file docker-compose.dev.yml up

version: 3
